import {specImg} from '~/utils/ui_v3_utils';

const SPEC_IMG = 'https://cdn.shopify.com/s/files/1/0703/9873/8521/files';

export const ArmourG2ProductSpecData = {
  primaryProductTitle: 'ARMOUR G2',
  secondaryProductTitle: 'ARMOUR GS2',
  isNoMaxWidthFinish: true,
  items: [
    {
      id: 'finish',
      itemTitle: 'Finish',
      itemType: 'color',
      primaryColorImages: [
        `${SPEC_IMG}/armour-g2-color-1.webp`,
        `${SPEC_IMG}/armour-g2-color-2.webp`,
      ],
      primaryColorTitle: [
        ['Carbon Fiber Gray', 'Silk Blue', 'Silk Silver', 'Mist Green'],
        ['Mist Pink', 'Dark Black', 'Racing Brown', 'Racing Red'],
      ],
      primaryColorImagesMobile: [
        `${SPEC_IMG}/armour-g2-color-mob-1.webp`,
        `${SPEC_IMG}/armour-g2-color-mob-2.webp`,
      ],
      primaryColorTitleMobile: [
        ['Carbon Fiber Gray', 'Silk Blue', 'Silk Silver', 'Mist Green'],
        ['Mist Pink', 'Dark Black', 'Racing Brown', 'Racing Red'],
      ],
      secondaryColorImages: [
        `${SPEC_IMG}/armour-gs2-color-1.webp`,
        `${SPEC_IMG}/armour-gs2-color-2.webp`,
      ],
      secondaryColorTitle: [
        ['Black Weave', 'Gunmetal Weave', 'Deep\nBlue', 'Pine\nGreen'],
        ['Sakura Pink', 'Silver\nTopo', '', ''],
      ],
      secondaryColorImagesMobile: [
        `${SPEC_IMG}/armour-gs2-color-mob-1.webp`,
        `${SPEC_IMG}/armour-gs2-color-mob-2.webp`,
      ],
      secondaryColorTitleMobile: [
        ['Black Weave', 'Gunmetal Weave', 'Deep Blue'],
        ['Pine Green', 'Sakura Pink', 'Silver Topo'],
      ],
    },
    {
      id: 'msrp',
      itemTitle: 'MSRP',
      itemType: 'textWithImage',
      primaryTextWithImage: ['$51.9'],
      secondaryTextWithImage: ['$48.9'],
    },
    {
      id: 'size',
      itemTitle: 'Size and weight',
      itemType: 'textWithImage',
      primaryTextWithImage: [
        specImg(`${SPEC_IMG}/armour-g2-size.webp`),
        'Dimensions: 113x39x28mm',
        'Weight: 222g',
      ],
      secondaryTextWithImage: [
        specImg(`${SPEC_IMG}/armour-gs2-size.webp`),
        'Dimensions: 126x39x28mm',
        'Weight: 214g',
      ],
    },
    {
      id: 'power',
      itemTitle: 'Power and battery',
      itemType: 'textWithImage',
      primaryTextWithImage: [
        'Battery Capacity: 3400mAh',
        'Output Power: 5-60W',
        'Charging Current: DC 9V/2A, 5V/3A Type-C',
        'Display: 0.96" TFT Screen',
      ],
      secondaryTextWithImage: [
        'Battery Capacity: 1 x 18650 Battery(Not Included)',
        'Output Power: 5-80W',
        'Charging Current: DC 5V/2A, Type-C',
        'Display: 0.96" TFT Screen',
      ],
    },
    {
      id: 'coil',
      itemTitle: 'Coil and pod',
      itemType: 'textWithImage',
      primaryTextWithImage: [
        '<Pod:>',
        'Armour G Series 5ml Pod (MTL & DTL)',
        '<GTX Dual Mesh Coil:>',
        '0.15Ω/ 0.2Ω/ 0.3Ω/ 0.4Ω',
        '<GTX Single Mesh Coil:>',
        '0.15Ω/ 0.2Ω/ 0.3Ω/ 0.4Ω/ 0.6Ω/ 0.8Ω/ 1.2Ω',
        '[Note:] 0.15Ω Not Compatible With Armour G2',
      ],
    },
    {
      id: 'packing',
      itemTitle: 'Packing list',
      itemType: 'textWithImage',
      primaryTextWithImage: [
        '<Global MTL Ver.  KIT INCLUDES>',
        '1 x VAPORESSO ARMOUR G2 Mod',
        '1 x VAPORESSO ARMOUR G SERIES POD(5ML/ MTL)  ',
        '1 x GTX 0.6Ω Mesh Coil(Pre-installed)',
        '1 x GTX 0.4Ω Dual Mesh Coil(In-box)',
        '1 x TYPE-C Cable',
        '1 x User Manual & Warranty Card',
        '1 x Reminder Card',
        specImg(
          `${SPEC_IMG}/armour-g2-package-MTL.webp`,
          `${SPEC_IMG}/armour-g2-package-MTL-mob.webp`,
        ),
        '<Global DTL Ver.  KIT INCLUDES>',
        '1 x VAPORESSO ARMOUR G2 Mod',
        '1 x VAPORESSO ARMOUR G SERIES POD(5ML/ DTL)',
        '1 x GTX 0.4Ω Dual Mesh Coil (Pre-installed)',
        '1 x GTX 0.2Ω Dual Mesh Coil (In-box)',
        '1 x TYPE-C Cable',
        '1 x User Manual & Warranty Card',
        '1 x Reminder Card',
        specImg(
          `${SPEC_IMG}/armour-g2-package-DTL.webp`,
          `${SPEC_IMG}/armour-g2-package-DTL-mob.webp`,
        ),
        '<TPD DTL Ver. KIT INCLUDES>',
        '1 x VAPORESSO ARMOUR G2 Mod',
        '1 x VAPORESSO ARMOUR G SERIES POD(2ML/ DTL)',
        '1 x GTX 0.4Ω Dual Mesh Coil (Pre-installed)',
        '1 x GTX 0.2Ω Dual Mesh Coil (In-box)',
        '1 x TYPE-C Cable',
        '1 x User Manual & Warranty Card',
        '1 x Reminder Card',
        specImg(
          `${SPEC_IMG}/armour-g2-package-TPD.webp`,
          `${SPEC_IMG}/armour-g2-package-TPD-mob.webp`,
        ),
      ],
      secondaryTextWithImage: [
        '<Global Ver.  KIT INCLUDES>',
        '1 x VAPORESSO ARMOUR GS2 Mod',
        '1 x VAPORESSO ARMOUR G SERIES POD(5ML/ DTL)',
        '1 x GTX 0.3Ω Dual Mesh Coil (Pre-installed)',
        '1 x GTX 0.15Ω Dual Mesh Coil (In-box)',
        '1 x TYPE-C Cable',
        '1 x User Manual & Warranty Card',
        '1 x Reminder Card',
        specImg(
          `${SPEC_IMG}/armour-gs2-package-DTL.webp`,
          `${SPEC_IMG}/armour-gs2-package-DTL-mob.webp`,
        ),
        '<TPD Ver. KIT INCLUDES>',
        '1 x VAPORESSO ARMOUR GS2 Mod',
        '1 x VAPORESSO ARMOUR G SERIES POD(2ML/ DTL)',
        '1 x GTX 0.3Ω Dual Mesh Coil (Pre-installed)',
        '1 x GTX 0.15Ω Dual Mesh Coil (In-box)',
        '1 x TYPE-C Cable',
        '1 x User Manual & Warranty Card',
        '1 x Reminder Card',
        specImg(
          `${SPEC_IMG}/armour-gs2-package-DTL-TPD.webp`,
          `${SPEC_IMG}/armour-gs2-package-DTL-TPD-mob.webp`,
        ),
      ],
    },
  ],
};
